import { v2 as cloudinary } from 'cloudinary';

/**
 * Cloudinary singleton — credentials read from env at import time.
 * API_SECRET stays on the backend; the frontend never sees it. Direct uploads
 * from the browser go to `api.cloudinary.com` using a signed signature
 * generated by `signUpload()` below.
 */
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true,
});

const ALLOWED_FOLDERS = new Set<string>(['properties', 'avatars']);
const ALLOWED_FOLDER_PREFIXES = ['properties/', 'avatars/'];

export interface SignedUploadPayload {
  signature: string;
  timestamp: number;
  cloudName: string;
  apiKey: string;
  folder: string;
  uploadUrl: string;
}

/**
 * Generates a signed upload payload that the browser uses to POST a file
 * directly to Cloudinary. We validate the folder against a whitelist so
 * a stolen signature cannot be reused to upload outside `properties/`.
 */
export function signUpload(folder: string): SignedUploadPayload {
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  const apiKey = process.env.CLOUDINARY_API_KEY;
  const apiSecret = process.env.CLOUDINARY_API_SECRET;

  if (!cloudName || !apiKey || !apiSecret) {
    throw new Error('Cloudinary credentials are not configured');
  }

  const safeFolder = folder?.trim() || process.env.CLOUDINARY_UPLOAD_FOLDER || 'properties';
  const isAllowed =
    ALLOWED_FOLDERS.has(safeFolder) ||
    ALLOWED_FOLDER_PREFIXES.some((p) => safeFolder.startsWith(p));
  if (!isAllowed) {
    throw new Error(`Folder "${safeFolder}" is not permitted`);
  }

  const timestamp = Math.round(Date.now() / 1000);
  // The params object must match EXACTLY what the browser sends in the form
  // (alphabetical order, same values), otherwise the signature is rejected.
  const signature = cloudinary.utils.api_sign_request({ folder: safeFolder, timestamp }, apiSecret);

  return {
    signature,
    timestamp,
    cloudName,
    apiKey,
    folder: safeFolder,
    uploadUrl: `https://api.cloudinary.com/v1_1/${cloudName}/image/upload`,
  };
}

/**
 * Extracts a Cloudinary `public_id` from a secure_url. Used only for
 * server-side deletes when a Property is removed.
 *
 *   https://res.cloudinary.com/{cloud}/image/upload/v123/properties/abc.jpg
 *   → "properties/abc"
 */
export function publicIdFromUrl(url: string): string | null {
  try {
    const u = new URL(url);
    const idx = u.pathname.indexOf('/upload/');
    if (idx === -1) return null;
    // Strip "/upload/" and a possible version segment "v123/"
    let rest = u.pathname.slice(idx + '/upload/'.length);
    rest = rest.replace(/^v\d+\//, '');
    // Drop extension
    const dot = rest.lastIndexOf('.');
    return dot > 0 ? rest.slice(0, dot) : rest;
  } catch {
    return null;
  }
}

/**
 * Best-effort delete of a single asset on Cloudinary. Never throws — the
 * Property delete must succeed even if the asset is already gone or the
 * Cloudinary API is briefly unreachable.
 */
export async function deleteAssetByUrl(url: string): Promise<void> {
  const publicId = publicIdFromUrl(url);
  if (!publicId) return;
  try {
    await cloudinary.uploader.destroy(publicId, { invalidate: true });
  } catch (e) {
    console.warn('[cloudinary] destroy failed for', publicId, e);
  }
}
